server:
  port: 8080
  servlet:
    context-path: /crawler

spring:
  application:
    name: crawler
  datasource:
    url: jdbc:mysql://101.132.116.166:3306/crawler
    username: root
    password: pass1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true